# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\LVGL\emscripten\lv_web_emscripten

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\LVGL\emscripten\lv_web_emscripten\cmbuild

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\LVGL\emscripten\lv_web_emscripten\cmbuild\CMakeFiles D:\LVGL\emscripten\lv_web_emscripten\cmbuild\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\LVGL\emscripten\lv_web_emscripten\cmbuild\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named index

# Build rule for target.
index: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 index
.PHONY : index

# fast build rule for target.
index/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/build
.PHONY : index/fast

#=============================================================================
# Target rules for targets named lvgl

# Build rule for target.
lvgl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 lvgl
.PHONY : lvgl

# fast build rule for target.
lvgl/fast:
	$(MAKE) $(MAKESILENT) -f lvgl\CMakeFiles\lvgl.dir\build.make lvgl/CMakeFiles/lvgl.dir/build
.PHONY : lvgl/fast

#=============================================================================
# Target rules for targets named lvgl_thorvg

# Build rule for target.
lvgl_thorvg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 lvgl_thorvg
.PHONY : lvgl_thorvg

# fast build rule for target.
lvgl_thorvg/fast:
	$(MAKE) $(MAKESILENT) -f lvgl\CMakeFiles\lvgl_thorvg.dir\build.make lvgl/CMakeFiles/lvgl_thorvg.dir/build
.PHONY : lvgl_thorvg/fast

#=============================================================================
# Target rules for targets named lvgl_examples

# Build rule for target.
lvgl_examples: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 lvgl_examples
.PHONY : lvgl_examples

# fast build rule for target.
lvgl_examples/fast:
	$(MAKE) $(MAKESILENT) -f lvgl\CMakeFiles\lvgl_examples.dir\build.make lvgl/CMakeFiles/lvgl_examples.dir/build
.PHONY : lvgl_examples/fast

#=============================================================================
# Target rules for targets named lvgl_demos

# Build rule for target.
lvgl_demos: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 lvgl_demos
.PHONY : lvgl_demos

# fast build rule for target.
lvgl_demos/fast:
	$(MAKE) $(MAKESILENT) -f lvgl\CMakeFiles\lvgl_demos.dir\build.make lvgl/CMakeFiles/lvgl_demos.dir/build
.PHONY : lvgl_demos/fast

examplelist.o: examplelist.c.o
.PHONY : examplelist.o

# target to build an object file
examplelist.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/examplelist.c.o
.PHONY : examplelist.c.o

examplelist.i: examplelist.c.i
.PHONY : examplelist.i

# target to preprocess a source file
examplelist.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/examplelist.c.i
.PHONY : examplelist.c.i

examplelist.s: examplelist.c.s
.PHONY : examplelist.s

# target to generate assembly for a file
examplelist.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/examplelist.c.s
.PHONY : examplelist.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/main.c.s
.PHONY : main.c.s

mouse_cursor_icon.o: mouse_cursor_icon.c.o
.PHONY : mouse_cursor_icon.o

# target to build an object file
mouse_cursor_icon.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/mouse_cursor_icon.c.o
.PHONY : mouse_cursor_icon.c.o

mouse_cursor_icon.i: mouse_cursor_icon.c.i
.PHONY : mouse_cursor_icon.i

# target to preprocess a source file
mouse_cursor_icon.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/mouse_cursor_icon.c.i
.PHONY : mouse_cursor_icon.c.i

mouse_cursor_icon.s: mouse_cursor_icon.c.s
.PHONY : mouse_cursor_icon.s

# target to generate assembly for a file
mouse_cursor_icon.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/mouse_cursor_icon.c.s
.PHONY : mouse_cursor_icon.c.s

ui/vintageradio/images/ui_image_needle_1.o: ui/vintageradio/images/ui_image_needle_1.c.o
.PHONY : ui/vintageradio/images/ui_image_needle_1.o

# target to build an object file
ui/vintageradio/images/ui_image_needle_1.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/ui/vintageradio/images/ui_image_needle_1.c.o
.PHONY : ui/vintageradio/images/ui_image_needle_1.c.o

ui/vintageradio/images/ui_image_needle_1.i: ui/vintageradio/images/ui_image_needle_1.c.i
.PHONY : ui/vintageradio/images/ui_image_needle_1.i

# target to preprocess a source file
ui/vintageradio/images/ui_image_needle_1.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/ui/vintageradio/images/ui_image_needle_1.c.i
.PHONY : ui/vintageradio/images/ui_image_needle_1.c.i

ui/vintageradio/images/ui_image_needle_1.s: ui/vintageradio/images/ui_image_needle_1.c.s
.PHONY : ui/vintageradio/images/ui_image_needle_1.s

# target to generate assembly for a file
ui/vintageradio/images/ui_image_needle_1.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/ui/vintageradio/images/ui_image_needle_1.c.s
.PHONY : ui/vintageradio/images/ui_image_needle_1.c.s

ui/vintageradio/images/ui_image_needle_2.o: ui/vintageradio/images/ui_image_needle_2.c.o
.PHONY : ui/vintageradio/images/ui_image_needle_2.o

# target to build an object file
ui/vintageradio/images/ui_image_needle_2.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/ui/vintageradio/images/ui_image_needle_2.c.o
.PHONY : ui/vintageradio/images/ui_image_needle_2.c.o

ui/vintageradio/images/ui_image_needle_2.i: ui/vintageradio/images/ui_image_needle_2.c.i
.PHONY : ui/vintageradio/images/ui_image_needle_2.i

# target to preprocess a source file
ui/vintageradio/images/ui_image_needle_2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/ui/vintageradio/images/ui_image_needle_2.c.i
.PHONY : ui/vintageradio/images/ui_image_needle_2.c.i

ui/vintageradio/images/ui_image_needle_2.s: ui/vintageradio/images/ui_image_needle_2.c.s
.PHONY : ui/vintageradio/images/ui_image_needle_2.s

# target to generate assembly for a file
ui/vintageradio/images/ui_image_needle_2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/ui/vintageradio/images/ui_image_needle_2.c.s
.PHONY : ui/vintageradio/images/ui_image_needle_2.c.s

ui/vintageradio/images/ui_image_vr_bands_bg_off.o: ui/vintageradio/images/ui_image_vr_bands_bg_off.c.o
.PHONY : ui/vintageradio/images/ui_image_vr_bands_bg_off.o

# target to build an object file
ui/vintageradio/images/ui_image_vr_bands_bg_off.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/ui/vintageradio/images/ui_image_vr_bands_bg_off.c.o
.PHONY : ui/vintageradio/images/ui_image_vr_bands_bg_off.c.o

ui/vintageradio/images/ui_image_vr_bands_bg_off.i: ui/vintageradio/images/ui_image_vr_bands_bg_off.c.i
.PHONY : ui/vintageradio/images/ui_image_vr_bands_bg_off.i

# target to preprocess a source file
ui/vintageradio/images/ui_image_vr_bands_bg_off.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/ui/vintageradio/images/ui_image_vr_bands_bg_off.c.i
.PHONY : ui/vintageradio/images/ui_image_vr_bands_bg_off.c.i

ui/vintageradio/images/ui_image_vr_bands_bg_off.s: ui/vintageradio/images/ui_image_vr_bands_bg_off.c.s
.PHONY : ui/vintageradio/images/ui_image_vr_bands_bg_off.s

# target to generate assembly for a file
ui/vintageradio/images/ui_image_vr_bands_bg_off.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/ui/vintageradio/images/ui_image_vr_bands_bg_off.c.s
.PHONY : ui/vintageradio/images/ui_image_vr_bands_bg_off.c.s

ui/vintageradio/images/ui_image_vr_bands_bg_on.o: ui/vintageradio/images/ui_image_vr_bands_bg_on.c.o
.PHONY : ui/vintageradio/images/ui_image_vr_bands_bg_on.o

# target to build an object file
ui/vintageradio/images/ui_image_vr_bands_bg_on.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/ui/vintageradio/images/ui_image_vr_bands_bg_on.c.o
.PHONY : ui/vintageradio/images/ui_image_vr_bands_bg_on.c.o

ui/vintageradio/images/ui_image_vr_bands_bg_on.i: ui/vintageradio/images/ui_image_vr_bands_bg_on.c.i
.PHONY : ui/vintageradio/images/ui_image_vr_bands_bg_on.i

# target to preprocess a source file
ui/vintageradio/images/ui_image_vr_bands_bg_on.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/ui/vintageradio/images/ui_image_vr_bands_bg_on.c.i
.PHONY : ui/vintageradio/images/ui_image_vr_bands_bg_on.c.i

ui/vintageradio/images/ui_image_vr_bands_bg_on.s: ui/vintageradio/images/ui_image_vr_bands_bg_on.c.s
.PHONY : ui/vintageradio/images/ui_image_vr_bands_bg_on.s

# target to generate assembly for a file
ui/vintageradio/images/ui_image_vr_bands_bg_on.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/ui/vintageradio/images/ui_image_vr_bands_bg_on.c.s
.PHONY : ui/vintageradio/images/ui_image_vr_bands_bg_on.c.s

ui/vintageradio/images/ui_image_vr_bands_bg_on_bt.o: ui/vintageradio/images/ui_image_vr_bands_bg_on_bt.c.o
.PHONY : ui/vintageradio/images/ui_image_vr_bands_bg_on_bt.o

# target to build an object file
ui/vintageradio/images/ui_image_vr_bands_bg_on_bt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/ui/vintageradio/images/ui_image_vr_bands_bg_on_bt.c.o
.PHONY : ui/vintageradio/images/ui_image_vr_bands_bg_on_bt.c.o

ui/vintageradio/images/ui_image_vr_bands_bg_on_bt.i: ui/vintageradio/images/ui_image_vr_bands_bg_on_bt.c.i
.PHONY : ui/vintageradio/images/ui_image_vr_bands_bg_on_bt.i

# target to preprocess a source file
ui/vintageradio/images/ui_image_vr_bands_bg_on_bt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/ui/vintageradio/images/ui_image_vr_bands_bg_on_bt.c.i
.PHONY : ui/vintageradio/images/ui_image_vr_bands_bg_on_bt.c.i

ui/vintageradio/images/ui_image_vr_bands_bg_on_bt.s: ui/vintageradio/images/ui_image_vr_bands_bg_on_bt.c.s
.PHONY : ui/vintageradio/images/ui_image_vr_bands_bg_on_bt.s

# target to generate assembly for a file
ui/vintageradio/images/ui_image_vr_bands_bg_on_bt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/ui/vintageradio/images/ui_image_vr_bands_bg_on_bt.c.s
.PHONY : ui/vintageradio/images/ui_image_vr_bands_bg_on_bt.c.s

ui/vintageradio/images/ui_image_vr_knob.o: ui/vintageradio/images/ui_image_vr_knob.c.o
.PHONY : ui/vintageradio/images/ui_image_vr_knob.o

# target to build an object file
ui/vintageradio/images/ui_image_vr_knob.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/ui/vintageradio/images/ui_image_vr_knob.c.o
.PHONY : ui/vintageradio/images/ui_image_vr_knob.c.o

ui/vintageradio/images/ui_image_vr_knob.i: ui/vintageradio/images/ui_image_vr_knob.c.i
.PHONY : ui/vintageradio/images/ui_image_vr_knob.i

# target to preprocess a source file
ui/vintageradio/images/ui_image_vr_knob.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/ui/vintageradio/images/ui_image_vr_knob.c.i
.PHONY : ui/vintageradio/images/ui_image_vr_knob.c.i

ui/vintageradio/images/ui_image_vr_knob.s: ui/vintageradio/images/ui_image_vr_knob.c.s
.PHONY : ui/vintageradio/images/ui_image_vr_knob.s

# target to generate assembly for a file
ui/vintageradio/images/ui_image_vr_knob.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/ui/vintageradio/images/ui_image_vr_knob.c.s
.PHONY : ui/vintageradio/images/ui_image_vr_knob.c.s

ui/vintageradio/images/ui_image_vr_main_body.o: ui/vintageradio/images/ui_image_vr_main_body.c.o
.PHONY : ui/vintageradio/images/ui_image_vr_main_body.o

# target to build an object file
ui/vintageradio/images/ui_image_vr_main_body.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/ui/vintageradio/images/ui_image_vr_main_body.c.o
.PHONY : ui/vintageradio/images/ui_image_vr_main_body.c.o

ui/vintageradio/images/ui_image_vr_main_body.i: ui/vintageradio/images/ui_image_vr_main_body.c.i
.PHONY : ui/vintageradio/images/ui_image_vr_main_body.i

# target to preprocess a source file
ui/vintageradio/images/ui_image_vr_main_body.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/ui/vintageradio/images/ui_image_vr_main_body.c.i
.PHONY : ui/vintageradio/images/ui_image_vr_main_body.c.i

ui/vintageradio/images/ui_image_vr_main_body.s: ui/vintageradio/images/ui_image_vr_main_body.c.s
.PHONY : ui/vintageradio/images/ui_image_vr_main_body.s

# target to generate assembly for a file
ui/vintageradio/images/ui_image_vr_main_body.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/ui/vintageradio/images/ui_image_vr_main_body.c.s
.PHONY : ui/vintageradio/images/ui_image_vr_main_body.c.s

ui/vintageradio/images/ui_image_vr_needle.o: ui/vintageradio/images/ui_image_vr_needle.c.o
.PHONY : ui/vintageradio/images/ui_image_vr_needle.o

# target to build an object file
ui/vintageradio/images/ui_image_vr_needle.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/ui/vintageradio/images/ui_image_vr_needle.c.o
.PHONY : ui/vintageradio/images/ui_image_vr_needle.c.o

ui/vintageradio/images/ui_image_vr_needle.i: ui/vintageradio/images/ui_image_vr_needle.c.i
.PHONY : ui/vintageradio/images/ui_image_vr_needle.i

# target to preprocess a source file
ui/vintageradio/images/ui_image_vr_needle.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/ui/vintageradio/images/ui_image_vr_needle.c.i
.PHONY : ui/vintageradio/images/ui_image_vr_needle.c.i

ui/vintageradio/images/ui_image_vr_needle.s: ui/vintageradio/images/ui_image_vr_needle.c.s
.PHONY : ui/vintageradio/images/ui_image_vr_needle.s

# target to generate assembly for a file
ui/vintageradio/images/ui_image_vr_needle.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/ui/vintageradio/images/ui_image_vr_needle.c.s
.PHONY : ui/vintageradio/images/ui_image_vr_needle.c.s

ui/vintageradio/vintageradio.o: ui/vintageradio/vintageradio.c.o
.PHONY : ui/vintageradio/vintageradio.o

# target to build an object file
ui/vintageradio/vintageradio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/ui/vintageradio/vintageradio.c.o
.PHONY : ui/vintageradio/vintageradio.c.o

ui/vintageradio/vintageradio.i: ui/vintageradio/vintageradio.c.i
.PHONY : ui/vintageradio/vintageradio.i

# target to preprocess a source file
ui/vintageradio/vintageradio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/ui/vintageradio/vintageradio.c.i
.PHONY : ui/vintageradio/vintageradio.c.i

ui/vintageradio/vintageradio.s: ui/vintageradio/vintageradio.c.s
.PHONY : ui/vintageradio/vintageradio.s

# target to generate assembly for a file
ui/vintageradio/vintageradio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/ui/vintageradio/vintageradio.c.s
.PHONY : ui/vintageradio/vintageradio.c.s

ui/vintageradio/vintageradio_audio.o: ui/vintageradio/vintageradio_audio.c.o
.PHONY : ui/vintageradio/vintageradio_audio.o

# target to build an object file
ui/vintageradio/vintageradio_audio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/ui/vintageradio/vintageradio_audio.c.o
.PHONY : ui/vintageradio/vintageradio_audio.c.o

ui/vintageradio/vintageradio_audio.i: ui/vintageradio/vintageradio_audio.c.i
.PHONY : ui/vintageradio/vintageradio_audio.i

# target to preprocess a source file
ui/vintageradio/vintageradio_audio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/ui/vintageradio/vintageradio_audio.c.i
.PHONY : ui/vintageradio/vintageradio_audio.c.i

ui/vintageradio/vintageradio_audio.s: ui/vintageradio/vintageradio_audio.c.s
.PHONY : ui/vintageradio/vintageradio_audio.s

# target to generate assembly for a file
ui/vintageradio/vintageradio_audio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\index.dir\build.make CMakeFiles/index.dir/ui/vintageradio/vintageradio_audio.c.s
.PHONY : ui/vintageradio/vintageradio_audio.c.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... install
	@echo ... install/local
	@echo ... install/strip
	@echo ... list_install_components
	@echo ... rebuild_cache
	@echo ... index
	@echo ... lvgl
	@echo ... lvgl_demos
	@echo ... lvgl_examples
	@echo ... lvgl_thorvg
	@echo ... examplelist.o
	@echo ... examplelist.i
	@echo ... examplelist.s
	@echo ... main.o
	@echo ... main.i
	@echo ... main.s
	@echo ... mouse_cursor_icon.o
	@echo ... mouse_cursor_icon.i
	@echo ... mouse_cursor_icon.s
	@echo ... ui/vintageradio/images/ui_image_needle_1.o
	@echo ... ui/vintageradio/images/ui_image_needle_1.i
	@echo ... ui/vintageradio/images/ui_image_needle_1.s
	@echo ... ui/vintageradio/images/ui_image_needle_2.o
	@echo ... ui/vintageradio/images/ui_image_needle_2.i
	@echo ... ui/vintageradio/images/ui_image_needle_2.s
	@echo ... ui/vintageradio/images/ui_image_vr_bands_bg_off.o
	@echo ... ui/vintageradio/images/ui_image_vr_bands_bg_off.i
	@echo ... ui/vintageradio/images/ui_image_vr_bands_bg_off.s
	@echo ... ui/vintageradio/images/ui_image_vr_bands_bg_on.o
	@echo ... ui/vintageradio/images/ui_image_vr_bands_bg_on.i
	@echo ... ui/vintageradio/images/ui_image_vr_bands_bg_on.s
	@echo ... ui/vintageradio/images/ui_image_vr_bands_bg_on_bt.o
	@echo ... ui/vintageradio/images/ui_image_vr_bands_bg_on_bt.i
	@echo ... ui/vintageradio/images/ui_image_vr_bands_bg_on_bt.s
	@echo ... ui/vintageradio/images/ui_image_vr_knob.o
	@echo ... ui/vintageradio/images/ui_image_vr_knob.i
	@echo ... ui/vintageradio/images/ui_image_vr_knob.s
	@echo ... ui/vintageradio/images/ui_image_vr_main_body.o
	@echo ... ui/vintageradio/images/ui_image_vr_main_body.i
	@echo ... ui/vintageradio/images/ui_image_vr_main_body.s
	@echo ... ui/vintageradio/images/ui_image_vr_needle.o
	@echo ... ui/vintageradio/images/ui_image_vr_needle.i
	@echo ... ui/vintageradio/images/ui_image_vr_needle.s
	@echo ... ui/vintageradio/vintageradio.o
	@echo ... ui/vintageradio/vintageradio.i
	@echo ... ui/vintageradio/vintageradio.s
	@echo ... ui/vintageradio/vintageradio_audio.o
	@echo ... ui/vintageradio/vintageradio_audio.i
	@echo ... ui/vintageradio/vintageradio_audio.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

